### ISSUE TITLE
Where can I find my shortcode?

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk#105]
Hey folks, thanks for releasing this package! 🙏 

The documentation refers to a `shortCode` or "Region specific merchant ID".

https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/master/packages/generator/README.md#usage

<img width="812" alt="Screen Shot 2020-02-18 at 10 14 22 PM" src="https://user-images.githubusercontent.com/28967/74807038-5012b300-529c-11ea-980b-b7c73aea8ab5.png">

**Where does this value come from?**

_It doesn't appear to be mentioned on https://developer.commercecloud.com/ or https://documentation.b2c.commercecloud.salesforce.com/ – am I missing something obivous?_

It seems to be used to construct the hostname the `commerce-sdk` makes requests to ... eg. `$SHORTCODE.api.commercecloud.salesforce.com`

Can I construct this value from my On Demand Sandbox URL? For example, if I had sandbox at `abcd-001.sandbox.us01.dx.commercecloud.salesforce.com` ... is there a relation to the short code?

Thanks!

**Comment by jbegleiter-sf** [comment]
Hey John, shortCode is currently provided for you by your product point of contact, Terence. I've assigned him to this issue and he should be able to help you shortly (no pun intended).

**Comment by TerenceSFDC** [comment]
Short code is provided directly by Salesforce.  In this case I've emailed you your short code :)
