### ISSUE TITLE
Where can I find my organization ID?

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk#109]
It is not clear from the documentation how you'd go about building your Organization ID.

By inspecting the SalesforceCommerceCloud/sfcc-sample-apps repo, it appears you can create it by concatenating the Realm ID + Instance ID:

`f_ecom_${COMMERCE_CLIENT_REALM_ID}_${COMMERCE_CLIENT_INSTANCE_ID}`

https://github.com/SalesforceCommerceCloud/sfcc-sample-apps/blob/5f2ca390106611582cbeb2ab9b977057c0a98d01/packages/storefront-lwc/scripts/api.example.mjs#L16-L22

It would be cool if the documentation made this explicit or alternatively, constructed this value you for you from the Realm ID + Instance ID. _Of course, it should also make it clear how/where to find those values._

Thanks for your patience with my noob getting started questions ;)

**Comment by jbegleiter-sf** [comment]
You've highlighted something we are actively discussing internally, and we agree that this needs to be more clear. The APIs are largely consistent in the treatment of this value with one exception (only in beta) for Einstein, for which the orgId is actually the realm.

Let me discuss internally with the team as to how we'd like to handle this, thanks for raising the issue.

**Comment by craigbrose** [comment]
Really great that in 2 years they still make it extremely hard to find.
