### ISSUE TITLE
Add "repository" and "homepage" fields to package.json

### ISSUE THREAD

**Issue by wjharney** [SalesforceCommerceCloud/commerce-sdk#130]
Currently, neither this repository nor the Commerce Cloud Developer Center are linked to on [npm](https://www.npmjs.com/package/commerce-sdk). Adding the standard `repository` and `homepage` fields to each package.json will add the specified links to each page ([example](https://www.npmjs.com/package/tslib)), and will improve the discoverability of those resources.

**Comment by gkhunger-sf** [comment]
Hey @wjharney,

We didn't realize we missed that. Thanks for letting us know.

Cheers,
Gaurav
