### ISSUE TITLE
mocking service

### ISSUE THREAD

**Issue by nestorneto** [SalesforceCommerceCloud/commerce-sdk#131]
I heard something about a mocking service in the docs but I cant find it. 

How can I use the mock service?

**Comment by jbegleiter-sf** [comment]
Hey @nestorneto ,

At this time the mock service is only available through the Commerce Cloud Developer Center ( https://developer.commercecloud.com/s/ ). If you navigate to a particular API reference, e.g. https://developer.commercecloud.com/s/api-details/a003k00000UHvp0AAD/commerce-cloud-developer-centershopperproducts?tabset-888ee=2 , and select a specific endpoint, you will see the mocking service on the right:

![ccdc_mocking_service](https://user-images.githubusercontent.com/48479252/76238126-c48aa300-6205-11ea-9cea-ef6b6fc85e8d.png)

Please ensure that you select "Mocking Service" from the dropdown on the right-hand-side.
