### ISSUE TITLE
Do we have a roadmap of the commerce-sdk somewhere?

### ISSUE THREAD

**Issue by danechitoaie** [SalesforceCommerceCloud/commerce-sdk#169]
Like to know how much coverage of the API the current version has? What comes in next versions?

**Comment by TerenceSFDC** [comment]
There isn't a published roadmap for the SDK at the moment.  The SDK covers 100% of the APIs from the Salesforce Commerce API, which are documented on the new [Commerce Cloud Developer Community](https://developer.commercecloud.com/s/api-reference).  We have recently added native support for Redis caching and are currently improving the logging within the SDK.
