### ISSUE TITLE
Do we have documented somewhere the functions/methods this API provides?

### ISSUE THREAD

**Issue by danechitoaie** [SalesforceCommerceCloud/commerce-sdk#180]
Do we have documented somewhere the functions/methods this API provides? The params each function/method expects, return values, etc?

**Comment by kalagarraj** [comment]
Hey Dan,

When using an IDE such as VSCode, the autocomplete feature lets you view the available method and class definitions, including parameters and return types. We currently do not have the SDK methods officially documented as the IDE autocomplete feature provides most of the documentation functionality. 

This [Sample Code](https://www.npmjs.com/package/commerce-sdk) section has few screenshots showing the autocomplete capability. 

In addition to documenting the APIs on the new [Commerce Cloud Developer Community](https://developer.commercecloud.com/s/api-reference) We have a [blog](https://engineering.salesforce.com/introducing-the-salesforce-commerce-sdk-e987dbf2fe95#Goals) that provides a great introduction to our SDK.

Please let us know if this answers your question or is this something you already tried and still looking for method level documentation?
