### ISSUE TITLE
Why was Einstein Recommendations Removed from the SDK?

### ISSUE THREAD

**Issue by rcbello** [SalesforceCommerceCloud/commerce-sdk#197]
We're currently working to add the Einstein Recommendations to our mobile apps which mainly uses OCAPI. Do you guys intend to remove Einstein Recommendations from commerce-sdk going forward?

**Comment by TerenceSFDC** [comment]
The Einstein Recommendations API has differences in the way it is constructed compared to the other Salesforce Commerce APIs. These differences include areas such as authorization/authentication, URI and parameter formatting, differences with site definitions, and some policy implementation differences. At this time we have decided to remove the API from the SDK and it will be moved to its own page in the [CCDC](https://developer.commercecloud.com/s/), outside of the collection of Salesforce Commerce APIs. In the future, if these discrepancies are addressed in later versions, we will look to bring it back into the SDK.
