### ISSUE TITLE
Error: 401 Unauthorized after a minute of client usage

### ISSUE THREAD

**Issue by dijs** [SalesforceCommerceCloud/commerce-sdk#236]
Can someone help me understand what I am doing wrong here?

I am receiving this 401 error after using the product client a few times.

I am creating an API which will be used to gather product data to be rendered at a storefront.

I don't really understand when I should be creating the shopper token, is it once, once per session, or upon every single request?

Same question goes for the product client, should I recreate it, or only ever use the one instance?

Here is my example code:

```js

async function getConfig() {
  const config = {
    headers: {},
    parameters: {
      clientId,
      organizationId,
      shortCode,
      siteId,
    },
  };
  const token = await helpers.getShopperToken(config, { type: 'guest' });
  config.headers['authorization'] = token.getBearerHeader();
  return config;
}

async function getProductClient() {
  return new Product.ShopperProducts(await getConfig());
}

async function test() {
  const client = await getProductClient();
  setInterval(async () => {
    const prod = await client.getProduct({ parameters: { id: '25592581M' } });
    console.log(prod.name);
  }, 10000);
}

test();
```

As you can see, every 10 seconds it spits out the correctly fetched product name. And then seemingly randomly, it starts failing after around 60s...

I have no clue what the issue is.

```bash
Floral Dress
Floral Dress
Floral Dress
Floral Dress
Floral Dress
Floral Dress
Floral Dress
(node:19722) UnhandledPromiseRejectionWarning: Error: 401 Unauthorized
```

**Comment by unandyala** [comment]
Hi Richard,

The token is good for 30mins. After that token expires and you get a 401 unauthorized error. You can reuse the token until it expires and then you need to get a new one.

You can log the the expiration time from the token 

` console.log(`Expires at ${new Date(token.decodedToken["exp"]*1000)}`);`

With regard to product client, you can reuse the client as long as you want. Just pass the refreshed token in the method call, otherwise it will use the token set in the ClientConfig

```
const token = await helpers.getShopperToken(getConfig(), { type: 'guest' });
const prod = await client.getProduct({ parameters: { id: '25592581M' }, headers:{authorization: token.getBearerHeader() } });
```

**Comment by unandyala** [comment]
here is the sample code

```
async function test() {
    const config = {
        headers: {},
        parameters: {
            clientId,
            organizationId,
            shortCode,
            siteId
        }
    };
    let token = undefined;
    let client = new Product.ShopperProducts(config);
    setInterval(async () => {
        try {
            if(!token) {
                token =  await helpers.getShopperToken(config, {type: 'guest'});
                console.log(`Retrieved new token, expires at ${new Date(token.decodedToken["exp"] * 1000)}`);
            }
            const prod = await client.getProduct({parameters: {id: '25592581M'}, headers: {authorization: token.getBearerHeader()}});
            console.log(prod.name);
        }
        catch(error){
            if (error.response && error.response.statusText === 'Unauthorized') {
                //token expired
               token = undefined;
            } else {
                throw error;
            }
        }
    }, 300000);
}
test();
```

**Comment by dijs** [comment]
I just ran a slightly modified version of your code and got the same issue I stated before. It fails after 60-70 seconds, not 30min.

```js
async function test() {
  const config = {
    headers: {},
    parameters: {
      clientId,
      organizationId,
      shortCode,
      siteId,
    },
  };
  let token = undefined;
  let client = new Product.ShopperProducts(config);
  try {
    if (!token) {
      token = await helpers.getShopperToken(config, { type: 'guest' });
      console.log(
        `Retrieved new token, expires at ${new Date(
          token.decodedToken['exp'] * 1000
        )}`
      );
    }
    setInterval(async () => {
      const prod = await client.getProduct({
        parameters: { id: '25592581M' },
        headers: { authorization: token.getBearerHeader() },
      });
      console.log(prod.name);
    }, 10000);
  } catch (error) {
    if (error.response && error.response.statusText === 'Unauthorized') {
      //token expired
      token = undefined;
    } else {
      throw error;
    }
  }
}
```

All I did was add code to trigger a product query every 10s.

Here is the output

```sh
Retrieved new token, expires at Wed Jul 15 2020 10:44:23 GMT+0300 (Eastern European Summer Time)
Floral Dress
Floral Dress
Floral Dress
Floral Dress
Floral Dress
Floral Dress
(node:73924) UnhandledPromiseRejectionWarning: Error: 401 Unauthorized
```

**Comment by unandyala** [comment]
Can you change the console.log that logs the expiration time to log the current time as well so that we know the period that the token is good for.

``` javascript
 console.log(
                `Retrieved new token, current time: ${new Date()}, expiration time: ${new Date(
                    token.decodedToken['exp'] * 1000
                )}`
            );
```

In your code, try-catch is in the `test` function not in the callback that `setInterval` calls. So when unauthorized error occurs on `client.getProduct(...)`,  it does not get a new token and retry

If you want the callback in setInterval to retry and run when the token expires then you need try-catch around `client.getProduct(...)` and then when token expires you need to get new token (similar to the code I mentioned above)

**Comment by dijs** [comment]
I was able to get this to work with the raw HTTP API's. Still not sure why we have such short token lifetimes.

But another issue has started. The exact same test code is now giving me this response:

```js
{
  title: 'Unknown',
  type: 'https://api.commercecloud.salesforce.com/documentation/error/v1/errors/unknown',
  detail: null
}
```

Any ideas why I would be receiving this?

**Comment by unandyala** [comment]
We are looking in to the token expiry issue and opened a bug on it.

**Comment by monkey-jeff** [comment]
@dijs We have located the issue.  There is a fix for this in the commerce-cloud-core package that is utilized by the SDK.  We are going to release a new version of the SDK tomorrow morning that will contain this fix.  Also, this did not seem to be an issue with versions 1.4.1 and earlier of the SDK.

Once the new version is released if you can test again to ensure that this issue has been resolved that would be very appreciated.

Cheers,
Jeff

**Comment by dbarbato-sf** [comment]
Hi @dijs, we've just released a new version of the commerce-sdk which addresses this issue.
Please could you validate this fix on your side.

Cheers,

Daniel

**Comment by dijs** [comment]
Thank you, I will check it out tomorrow!

**Comment by dijs** [comment]
2.0.0 seems to have fixed the issue. Thank you!
