### ISSUE TITLE
Can i integrate this sdk for mobile apps, which platform it supports to work for Mobile platform?

### ISSUE THREAD

**Issue by jbegleiter-sf** [SalesforceCommerceCloud/commerce-sdk#242]
Can i integrate this sdk for mobile apps, which platform it supports to work for Mobile platform?
can you please suggest me the process of integrating the sdk fro mobile.

_Originally posted by @saivenkatesh48 in https://github.com/SalesforceCommerceCloud/commerce-sdk/pull/241#issuecomment-660035089_

**Comment by jbegleiter-sf** [comment]
@saivenkatesh48 as of right now this SDK is meant to work in node.js applications (a back-end JavaScript runtime). If you run such a back-end you could query it from a mobile app (or any commerce storefront experience). Could you give us a little more detail about what it is you'd like to do in mobile?

**Comment by saivenkatesh48** [comment]
What I am doing is , I have developed a react native mobile app and trying to integrate the sdk in the same app by running "npm insatll commerce-sdk", but I am facing issues with the integration. Is what I am doing is correct or not?

You mentioned the sdk as back end server, means can I develop the sdk on some server and from there I need to call the Restful APIs or any other way?

My requirement is , to integrate the sdk in the front end mobile app, but I didn't find the way of integration.

I want to integrate the sdk in any cross platform like Reactnative or Flutter or anything, can you let me know the process of integration.

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

Is it reasonable to assume that an SDK that works with React would work, or is this specific to React native mobile?

Cheers,
Josh

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

The SDK currently only supports node.js runtimes (Node versions 10, 12, and 14). We have not worked to explicitly make it work for React native, and in fact this SDK is intended to work in a backend for security reasons.

We can file an enhancement for this if you require the SDK to work in React native.

Cheers,
Josh

**Comment by saivenkatesh48** [comment]
Hi @jbegleiter-sf 
Based on your comments, I came to know is the SDK runs on node js back end server and from there we can query data by using APIs call and integrate that in our Mobile app, is that correct?

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

That is exactly correct. Is there anything else I can help you with today?

Cheers,
Josh

**Comment by saivenkatesh48** [comment]
@jbegleiter-sf 
one more help , if we deploy this SDK in server, after I have to write my own API calls or can I use the APIs that provided from the SDK to integrate in my Mobile app.

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

I'm not entirely sure what you mean. In our sample app ( https://github.com/SalesforceCommerceCloud/sfcc-sample-apps ) we recommend the use of GraphQL (Apollo server and client), and the sample app has examples of using the SDK in resolvers. I believe there is an authorization issue in this sample app currently that might make it difficult to test, but as an example I believe it will prove useful for your implementation.

Cheers,
Josh

**Comment by saivenkatesh48** [comment]
>Josh comment: We can file an enhancement for this if you require the SDK to work in React native.

I need the SDK support for React Native can you please file an enhancement for the SDK.

**Comment by jbegleiter-sf** [comment]
Hey @saivenkatesh48 ,

We'll file an enhancement on our side with a link to this issue. Unfortunately I cannot tell you when we would be able to deliver this. I'm going to close the issue for now but I will link it in our internal tracking system and ensure that it is linked in any future related PR.

Cheers,
Josh
