### ISSUE TITLE
Cannot read property 'native' of undefined

### ISSUE THREAD

**Issue by aleBarbiero** [SalesforceCommerceCloud/commerce-sdk#251]
TypeError: Cannot read property 'native' of undefined

I get this error only importing "commerce-sdk" on my project. I've tried with Node v12 and Node v10.
Any asuggestion? Thanks

**Comment by monkey-jeff** [comment]
Hi @aleBarbiero,

We test natively in node 10 and node 12.  Can you please provide some sample code that isn't working for you or a link to a repository so we can recreate the issue you are having?

Cheers,

Jeff

**Comment by aleBarbiero** [comment]
Hi @monkey-jeff 
you can find my code here:
https://github.com/aleBarbiero/headlessCommerce/blob/master/src/dataAPI.js

I've tried to comment each line except for the first one (the "include" one) and I'm always facing the same error. Thank you for your time and your help.

**Comment by monkey-jeff** [comment]
HI @aleBarbiero,

Looking at your package.json I don't see the commerce-sdk dependency.  I checked out your code, ran an `npm install --save commerce-sdk` or `yarn add commerce-sdk` and reran `yarn build` and it seems to resolve the issue.

Can you please try this and confirm?

-Jeff

**Comment by aleBarbiero** [comment]
My mistake, I forgot to add the file before committing. 
Now I have updated but nothing changes, always the same error.

**Comment by monkey-jeff** [comment]
Hi @aleBarbiero 

Thanks for the update. After further testing, I realized we were pulling in too many dependencies in a dependent package of @commerce-apps/core. I have added a PR to fix this in the @commerce-apps/core package (currently still a private repository, but should be public soon)

Once this has been updated you will no longer have the immediate issue you are describing, but it won't completely solve it either.

This leads me to a classic bad news good news situation. The bad news is we have built this SDK to run in a node environment or BFF, not within REACT.  Specifically, once this issue is fixed you will see a bunch of conflicts with make-fetch-happen.  The good news is we are currently working to prioritize a light-weight version of the SDK that is capable of running in a react app.  

I will save your app to ensure it works with this new SDK when we work on this.

Cheers,
Jeff

**Comment by aleBarbiero** [comment]
Hi @monkey-jeff 
thanks for your update. So I understand that I've to change my front-end if I want to use this SDK on my app right now.
Have you got any suggestion for me to switch from React to any other supported system? Thank you so much

**Comment by monkey-jeff** [comment]
Hi @aleBarbiero, 

We currently have a sample application demonstrating how to do this at https://github.com/SalesforceCommerceCloud/sfcc-sample-apps

Basically the current pattern is a separation of your application's frontend with a BFF.  This SDK used that BFF to communicate with the APIs as an intermediary.

We have taken the request for a React-capable SDK and are prioritizing it. We’ll link this issue to the PR when it is complete, timeline TBD.

Cheers,
Jeff

**Comment by dlferro** [comment]
@monkey-jeff has core been updated? I believe I have a related issue with make-fetch-happen when it attempts to leverage types.
```
node_modules/@commerce-apps/core/dist/base/staticClient.d.ts:1:10 - error TS2614: Module '"make-fetch-happen"' has no exported member 'Response'. Did you mean to use 'import Response from "make-fetch-happen"' instead?

1 import { Response, RequestInit } from "make-fetch-happen";
           ~~~~~~~~

node_modules/@commerce-apps/core/dist/base/staticClient.d.ts:1:20 - error TS2614: Module '"make-fetch-happen"' has no exported member 'RequestInit'. Did you mean to use 'import RequestInit from "make-fetch-happen"' instead?

1 import { Response, RequestInit } from "make-fetch-happen";
```

**Comment by unandyala** [comment]
Hi @dlferro 
What version of commerce-sdk are you using? I am not seeing this issue with the latest version 2.1.0. Can you please try with the latest version on SDK?

**Comment by dlferro** [comment]
I am at 2.1.0. It appears that this leverages version 8.0.10 of [make-fetch-happen](https://github.com/npm/make-fetch-happen/blob/v8.0.10/index.js) which doesn't include those types/classes.

**Comment by unandyala** [comment]
Hi @dlferro,

What is the node version you are using? Can you provide a link to your repository so we can recreate the issue you are having

Thanks
Ujwala

**Comment by jbegleiter-sf** [comment]
Hey @dlferro ,

We haven't heard back from you. I'm going to close this issue, but please feel free to reopen if you are still impacted.

Cheers,
Josh
