### ISSUE TITLE
commerce-sdk.code-workspace file has been deleted from repo

### ISSUE THREAD

**Issue by jorgehernandezSF** [SalesforceCommerceCloud/commerce-sdk#276]
In the https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/master/vscode/vscode.md readme, there is a mention of the commerce-sdk.code-workspace file that allows you to setup the commerce-sdk as a workspace.

The file is now missing, not sure if that was intentional or an omission.  Please put it back if still being used, or remove the /blob/master/vscode/vscode.md if not longer applicable.

**Comment by unandyala** [comment]
Hi @jorgehernandezSF,

The only section that is still relevant is "Debugging Tests" section. We will fix the vscode.md.

Thanks
Ujwala

**Comment by unandyala** [comment]
Hi @jorgehernandezSF,

 vscode documentation is now fixed.

Cheers,
Ujwala
