### ISSUE TITLE
Shopper Login (SLAS) missed getPasswordResetToken and resetPassword methods

### ISSUE THREAD

**Issue by a-dzhus** [SalesforceCommerceCloud/commerce-sdk#369]
Methods getPasswordResetToken and resetPassword are missed for Shopper Login (SLAS) (v.2.8.0) but mentioned in the release [changelog ](https://github.com/SalesforceCommerceCloud/commerce-sdk/blob/master/CHANGELOG.md) and [B2C Commerce API](https://developer.salesforce.com/docs/commerce/commerce-api/references/shopper-login?meta=getPasswordResetToken)

**Comment by a-dzhus** [comment]
@johnboxall https://github.com/orgs/SalesforceCommerceCloud/teams/commerce-cloud-services can you guys please have a look into this? Thanks!

**Comment by joeluong-sfcc** [comment]
Hi @a-dzhus, thanks for creating this issue! The team is taking a look into this

**Comment by joeluong-sfcc** [comment]
Hi @a-dzhus we've been able to confirm and reproduce this issue. I'll go ahead and create a work item in our backlog and we'll loop you in once this issue gets resolved!
