### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by amirshaheen** [SalesforceCommerceCloud/commerce-sdk#384]
Note: I am using demo client credentials as Environment Variables 

TypeError: Cannot read properties of undefined (reading 'map')
--
20:42:38.599 | at getProducts (/vercel/path0/.next/server/chunks/495.js:54:42)
20:42:38.599 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
20:42:38.599 | at async getStaticPaths (/vercel/path0/.next/server/pages/products/[slug].js:79:28)
20:42:38.600 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:598:33)
20:42:38.600 | at async /vercel/path0/node_modules/next/dist/build/utils.js:933:115
20:42:38.600 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
20:42:38.600 |  
20:42:38.600 | > Build error occurred
20:42:38.602 | Error: Failed to collect page data for /products/[slug]
20:42:38.602 | at /vercel/path0/node_modules/next/dist/build/utils.js:963:15
20:42:38.602 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
20:42:38.602 | type: 'Error'
20:42:38.602 | }
20:42:38.635 | error Command failed with exit code 1.
20:42:38.635 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:42:38.654 | Error: Command "yarn run build" exited with 1
20:42:38.764 | [dpl_BwidwZ4UEthzTvy9Da5HKyohBQkM][AF9h2nR6axdCqoBdhNrj6cYS] Command "yarn run build" exited with 1
20:42:38.784 | {"buildId":"bld_5e0m7xvb5","deploymentId":"dpl_BwidwZ4UEthzTvy9Da5HKyohBQkM","projectId":"prj_AyvvB7TQM4uhZGb3TrSG5iboz2Nm","ownerId":"AF9h2nR6axdCqoBdhNrj6cYS","name":"bld_5e0m7xvb5","source":"build","host":"salesforce-commerce-cloud-starter-i7z0v1q98.vercel.app","entrypoint":".","events":[{"id":"1676043758764885017531500000","timestamp":1676043758764,"message":"Command \"yarn run build\" exited with 1","type":"stderr"}]}

**Comment by joeluong-sfcc** [comment]
Hi @amirshaheen, could you provide steps to reproduce this, including version of the SDK you're using?

**Comment by joeluong-sfcc** [comment]
Hi @amirshaheen, I'll be closing out this issue if this is not reproducible, but please feel free to reopen it if you'd like us to follow up.
