### ISSUE TITLE
Remove deprecated `helpers.getShopperToken` method

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk#385]
Under the covers, `helpers.getShopperToken()` is powered by the deprecated SCAPI `/actions/login` method.

The method is generally unavailable and will be disabled for the majority of customers on March 31, 2023.

Customers should instead use the SLAS helpers introduced in #356:

* https://salesforcecommercecloud.github.io/commerce-sdk/modules/helpers.html#loginguestuserprivate
* https://salesforcecommercecloud.github.io/commerce-sdk/modules/helpers.html#loginregistereduserb2cprivate

To reduce confusion, we should remove the method!

While we're at it, we should also update the examples in the README to focus on the private helpers, which the vast majority of folks using this SDK should use: https://github.com/SalesforceCommerceCloud/commerce-sdk#sample-code

---

For folks looking to transition to SLAS, big picture you'll need to:

1. [Set permissions to configure SLAS in Account Manager](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-shopper-apis.html#set-up-user-roles-and-filters).
2. Create a SLAS private client for use in you BFF. You can do this programmatically, using the [SLAS Admin API](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-shopper-apis.html#advanced-slas-admin-api) or manually, using the [SLAS Admin UI](https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-shopper-apis.html#create-a-slas-client).
3. Update your code to call the `commerce-sdk` SLAS helper methods [`helpers.loginGuestUserPrivate`](https://salesforcecommercecloud.github.io/commerce-sdk/modules/helpers.html#loginguestuserprivate) and [`helpers.loginRegisteredUserB2Cprivate`](https://salesforcecommercecloud.github.io/commerce-sdk/modules/helpers.html#loginregistereduserb2cprivate) instead of `helpers.getShopperToken`.

To help familiarize yourself with SLAS and its concepts, checkout these docs:

* https://developer.salesforce.com/docs/commerce/commerce-api/guide/authorization-for-shopper-apis.html
* https://developer.salesforce.com/docs/commerce/commerce-api/guide/slas-private-client.html

A few more notes for your implementation:

* Subscribe to SLAS maintenance updates here: https://status.salesforce.com/products/B2C_Commerce_Cloud
* Consider using correlation IDs when making requests to SCAPI: https://developer.salesforce.com/docs/commerce/commerce-api/guide/identifying-requests-and-responses.html
* Review the SLAS Rate Limits: https://developer.salesforce.com/docs/commerce/commerce-api/guide/throttle-rates.html#shopper-login-(slas)
* If you’re re-using the same guest JWTs across requests, make sure you’re using multiple ones to avoid having all your requests hit a single app server: https://developer.salesforce.com/docs/commerce/commerce-api/guide/get-started.html#constraints

**Comment by joeluong-sfcc** [comment]
`getShopperToken` has been removed with the latest release, `v3.0.0`: https://github.com/SalesforceCommerceCloud/commerce-sdk/releases/tag/v3.0.0
