### ISSUE TITLE
searchProduct lacks expands parameter in types

### ISSUE THREAD

**Issue by michaelKurowski** [SalesforceCommerceCloud/commerce-sdk#387]
The API docs suggest that one can use `expand` parameter, but there's no such thing in the SCAPI SDK types.
Docs:
https://developer.salesforce.com/docs/commerce/commerce-api/references/shopper-search?meta=productSearch

**Comment by vcua-mobify** [comment]
Thanks for reporting this.

I'll add a work item to update the type and include that parameter.
