### ISSUE TITLE
Support Custom Properties 

### ISSUE THREAD

**Issue by iSreekanth** [SalesforceCommerceCloud/commerce-sdk#394]
Based on the article below, we should be able to send the custom query parameters to SCAPI.

https://developer.salesforce.com/docs/commerce/commerce-api/references/about-commerce-api/about.html#08302023

We tested this in Postman and working fine there. However, we don't see this support yet in SDK.

We have gone through the 2.11.2 (latest) docs for the product method but didn't find it. Below is a screenshot for the same.

<img width="944" alt="image" src="https://github.com/SalesforceCommerceCloud/commerce-sdk/assets/95233740/bc04904c-aaba-4e28-96c4-2b6b97b7d667">

Could you please let us know if we are missing something? If not, please share some info on this.

Thanks,
Sreekanth

**Comment by vmarta** [comment]
Hi @iSreekanth, that's right. The SDK does not currently support the custom query parameters. I'll bring this up with the team.

**Comment by joeluong-sfcc** [comment]
Hi @iSreekanth, although custom query parameters aren't fully supported yet with typescript, the `commerce-sdk` doesn't filter custom query parameters. If you pass a custom query parameter with plain JS (or suppress the typescript error), it'll get passed onto the underlying SCAPI call

**Comment by joeluong-sfcc** [comment]
Hi @iSreekanth, support for custom query parameters has been released with `v2.13.0`: https://github.com/SalesforceCommerceCloud/commerce-sdk/releases/tag/v2.13.0

I'll be closing out this issue, but feel free to reach out if you have any further questions.
