### ISSUE TITLE
[FEATURE] Add product search v24.3 perPriceBook and allVariationProperties support

### ISSUE THREAD

**Issue by JonasReniers** [SalesforceCommerceCloud/commerce-sdk#401]
We are currently working to eliminate the custom attributes exposed by a custom hook in order to display strike-through prices in PWA-kit by using the list, sale, and promotional prices on the PLP. To achieve this, we need to utilize the perPriceBook and allVariationProperties query parameters. Unfortunately, the Commerce SDK does not yet support these new query parameters. 

Link to the relevant documentation:
[https://developer.salesforce.com/docs/commerce/commerce-api/references/shopper-search?meta=productSearch](url)

Could we consider adding support for this feature?

**Comment by vmarta** [comment]
Hi @JonasReniers the new v2.15.0 release now supports those query parameters. https://github.com/SalesforceCommerceCloud/commerce-sdk/releases/tag/v2.15.0
